# Generated by Django 5.0.2 on 2024-03-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="inventory",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
